// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJyYwTv9Hdl0P_nLHHs8ZnOsZ6eoH0Es',
    appId: '1:228156748282:web:e2ee784c081bc27b093443',
    messagingSenderId: '228156748282',
    projectId: 'mobile-takekar',
    authDomain: 'mobile-takekar.firebaseapp.com',
    storageBucket: 'mobile-takekar.firebasestorage.app',
    measurementId: 'G-GDJCW2MFHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6Tes1Z9ifAkxge1shh861nNEoRBuFok',
    appId: '1:228156748282:android:d681806f61900439093443',
    messagingSenderId: '228156748282',
    projectId: 'mobile-takekar',
    storageBucket: 'mobile-takekar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUjewyHTJxaWZrgzaEQNtbkoELQ--5Bw',
    appId: '1:228156748282:ios:ebbf083a68bc5bec093443',
    messagingSenderId: '228156748282',
    projectId: 'mobile-takekar',
    storageBucket: 'mobile-takekar.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUjewyHTJxaWZrgzaEQNtbkoELQ--5Bw',
    appId: '1:228156748282:ios:ebbf083a68bc5bec093443',
    messagingSenderId: '228156748282',
    projectId: 'mobile-takekar',
    storageBucket: 'mobile-takekar.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJyYwTv9Hdl0P_nLHHs8ZnOsZ6eoH0Es',
    appId: '1:228156748282:web:19a44795cbbb0740093443',
    messagingSenderId: '228156748282',
    projectId: 'mobile-takekar',
    authDomain: 'mobile-takekar.firebaseapp.com',
    storageBucket: 'mobile-takekar.firebasestorage.app',
    measurementId: 'G-FFWRXMNV8L',
  );
}
